### ISSUE TITLE
panic: decoding receipt: bindnode TODO: invalid key: "allocated" is not a field in type Success

### ISSUE THREAD

**Issue by neoiss** [web3-storage/go-w3up#1]
I conducted an upload test according to the documentation, but when I called StoreAdd, I received the following error:" 
**panic: decoding receipt: bindnode TODO: invalid key: "allocated" is not a field in type Success**

doc: https://web3.storage/docs/go-w3up/#upload-a-car

**Comment by sudeepdino008** [comment]
same issue

**Comment by sudeepdino008** [comment]
in general give that the current upload mechanism's quality is going to degrade after Jan 9th; I'm surprised that the repo is not feature complete yet.
